### ISSUE TITLE
Got a error if `columns.locale` is `zh-CN`

### ISSUE THREAD

**Issue by zqjimlove** [jy95/i18n-tools#61]
**At least a duplicated value in files JSON object was detected**
```json
{"columns":[{"locale":"en","label":"en"},{"locale":"zh-CN","label":"zh-CN"}],"files":{"en":"/translations/en/translation.json","zh-CN":"/translations/zh-CN/translation.json"},"filename":"translation","outputDir":"/Users/hujin/Projects/socialFi/alienswap-app/temp"}
```

**Comment by jy95** [comment]
Hello,

Thanks for the report - it seems thrown by this [line](https://github.com/jy95/i18n-tools/blob/master/src/checks/export/export_common_checks.ts#L35).
```js
uniq(Object.values(files)).length !== entries.length
```

Obviously, it is an issue of yargs as your entries are differents (and my tests in local passed if I replaced "DE" by "zh-CN") ...
While I investigate that, @zqjimlove can you please check with previous versions of [i18n-tools](https://github.com/jy95/i18n-tools) when this regression occurred ?

I will keep you informed
